[package]
name = "httpr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
env_logger = "0.11.6"
log = "0.4.25"
strum = "0.26.3"
strum_macros = "0.26.4"

[dependencies.uuid]
version = "1.12.1"
features = ["v4"]
